[package]
name = "le-bitset"
description = "Little-endian bitset"
version = "0.1.3"
edition = "2021"
license-file = "LICENSE"

[features]
serde = ["dep:serde", "serde_derive"]

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
